---
title: "TG15 manuscript"
author: "David Cameron, Mike Dietze and Marcel van Oijen"
date: '`r Sys.Date()`'
output:
#  slidy_presentation: default
#   html_document: default
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    keep_tex: true
#  beamer_presentation:
#    incremental: true
#    includes:
#      in_header: mystyles.sty
#  word_document: default
---
 
```{r include=FALSE}
### SETTINGS
library(BayesianTools)
library(tidyverse)
library(gridExtra)
CLEAN.BUILD = FALSE

## PLOT.DIAGNOSTICS = TRUE
defParms = c(1,3,5,6,9,10) 
#exptPath = "RDataWorkingDellLong/"
exptPath = "~/OneDrive - NERC/COST/TG15/RDataWorkingMSILong/"
```

```{r child = 'introduction.Rmd'}
```

```{r child = 'methods.Rmd'}
```

```{r child = 'results.Rmd'}
```

```{r child = 'discussion.Rmd'}
```


<!-- <\!-- ```{r child = 'TG15-plans.Rmd'} -\-> -->
<!-- <\!-- ``` -\-> -->

<!-- ```{r child = 'TG15-intro-beamer.Rmd'} -->
<!-- ``` -->
<!-- ```{r child = 'TG15-results-beamer.Rmd'} -->
<!-- ``` -->




  
